#set heading(numbering: "1.")
#set math.equation(numbering: "(1)")

#include "a01-modulo.typ"
#include "a02-group.typ"
#include "a03-field.typ"
#include "a04-order.typ"
#include "a05-polynomial-ring.typ"
#include "a06-decomp.typ"
#include "a07-roots-of-unity.typ"
#include "a08-cyclotomic-polynomial.typ"
#include "a09-cyclotomic-polynomial-integer-ring.typ"
#include "a10-matrix.typ"
#include "a11-euler.typ"
#include "a12-modulus-rescaling.typ"
#include "a13-chinese-remainder.typ"
#include "a14-taylor-series.typ"
#include "a15-polynomial-interpolation.typ"
#include "a16-ntt.typ"
#include "b01-lattice.typ"
#include "b02-lwe.typ"
#include "b03-rlwe.typ"
#include "b04-glwe.typ"
#include "b05-glev.typ"
#include "b06-ggsw.typ"
#include "c01-glwe-add-cipher.typ"
#include "c02-glwe-add-plain.typ"
#include "c03-glwe-mult-plain.typ"
#include "c04-glwe-modulus-switch.typ"
#include "c05-glwe-key-switching.typ"
#include "d01-tfhe.typ"
#include "d02-bfv.typ"
#include "d03-ckks.typ"
#include "d04-bgv.typ"
#include "d05-rns.typ"
#include "d06-scheme-summary.typ"
#include "d07-python-demo-library.typ"